version: "3.9"
services:
  frontend:
    container_name: frontend
    image: node:18
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "npm i && npm run start"
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s