version: "3.9"
services:
  frontend:
    container_name: frontend
    image: node:18
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "80:3000"
    command: bash -c "npm i && npm run start"