version: '3.8'

x-quorum-def: &quorum-def
    restart: 'on-failure'
    image: '${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:latest}'
    expose:
        - '21000'
        - '50400'
    healthcheck:
        test:
            [
                'CMD',
                'wget',
                '--spider',
                '--proxy',
                'off',
                'http://localhost:8545',
            ]
        interval: 4s
        timeout: 4s
        retries: 10
        start_period: 5s
    labels:
        com.quorum.consensus: raft
    entrypoint:
        - /bin/sh
        - -c
        - |
            DDIR=/qdata/dd
            mkdir -p $${DDIR}/keystore
            mkdir -p $${DDIR}/geth
            cp /3nodes/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
            cp /3nodes/keys/key$${NODE_ID} $${DDIR}/keystore/
            cat /3nodes/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
            cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
            cat $${DDIR}/static-nodes.json
            GENESIS_FILE="/3nodes/genesis.json"
            NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
            GETH_ARGS_raft="--raft --raftport 50400"
            geth --datadir $${DDIR} init $${GENESIS_FILE}
            geth \
              --allow-insecure-unlock \
              --identity node$${NODE_ID}-raft \
              --datadir $${DDIR} \
              --permissioned \
              --nodiscover \
              --verbosity 5 \
              --networkid $${NETWORK_ID} \
              --rpc \
              --rpccorsdomain "*" \
              --rpcvhosts "*" \
              --rpcaddr 0.0.0.0 \
              --rpcport 8545 \
              --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft \
              --port 21000 \
              --unlock 0 \
              --password /3nodes/passwords.txt \
              ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_raft}



services:

    quorum-node1:
        <<: *quorum-def
        hostname: quorum-node1
        ports:
            - '22000:8545'
        volumes:
            # - vol1:/qdata
            - ./quorum-network:/3nodes:ro
            - ${dir_name}/docker_timezone:/etc/localtime:ro
        environment:
            - PRIVATE_CONFIG=ignore
            - NODE_ID=1
        networks:
            infrachain-network:
            quorum-simple-net:
                ipv4_address: 172.16.239.11
    quorum-node2:
        <<: *quorum-def
        hostname: quorum-node2
        ports:
            - '22001:8545'
        volumes:
            # - vol2:/qdata
            - ./quorum-network:/3nodes:ro
            - ${dir_name}/docker_timezone:/etc/localtime:ro
        environment:
            - PRIVATE_CONFIG=ignore
            - NODE_ID=2
        networks:
            infrachain-network:
            quorum-simple-net:
                ipv4_address: 172.16.239.12
    quorum-node3:
        <<: *quorum-def
        hostname: quorum-node3
        ports:
            - '22002:8545'
        volumes:
            # - vol3:/qdata
            - ./quorum-network:/3nodes:ro
            - ${dir_name}/docker_timezone:/etc/localtime:ro
        environment:
            - PRIVATE_CONFIG=ignore
            - NODE_ID=3
        networks:
            infrachain-network:
            quorum-simple-net:
                ipv4_address: 172.16.239.13

networks:
    quorum-simple-net:
        name: quorum-simple-net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.239.0/24
    infrachain-network:
        name: infrachain-network

volumes:
    'vol1':
    'vol2':
    'vol3':
